### ISSUE TITLE
models文件来源

### ISSUE THREAD

**Issue by banyedy** [JovenChu/embedding_model_test#1]
你好我想问一下”将模型下载到models文件夹中“是将什么文件加入进去了，我试了将ernie-3.0-base-zh模型文件加入发现出现了这样的错误：
![image](https://github.com/JovenChu/embedding_model_test/assets/101393078/7000d02f-c7f1-491f-af13-ed90e719b3fc)
可以提供一下模型相应的地址吗？非常感谢！

**Comment by JovenChu** [comment]
你好，都是通过huggingface下载的，下载地址在模型测试的【对比模型】链接中
<img width="869" alt="image" src="https://github.com/JovenChu/embedding_model_test/assets/26185132/5af0786b-00fc-4eae-a11a-bf721bcb9591">
如果能正常输出图像文件，即可运行成功，否则请检查模型文件是否完整生成。
![image](https://github.com/JovenChu/embedding_model_test/assets/26185132/b2fa7902-1a94-42dd-8029-ac037d240b58)
